### ISSUE TITLE
Missing dependency or library when including typsense-java 0.9.0

### ISSUE THREAD

**Issue by lm-aols** [typesense/typesense-java#67]
## Description

When trying to instantiate a Typesense Client, I get a NoClassDefFoundError

## Steps to reproduce

I have added the following to my pom.xml:
```
<dependency>
            <groupId>org.typesense</groupId>
            <artifactId>typesense-java</artifactId>
            <version>0.9.0</version>
</dependency>
```

When I try to instantiate a `Client`, I get the following stack trace (Edited for anonymity)
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.typesense.api.ApiCall
        at org.typesense.api.Client.<init>(Client.java:28) ~[typesense-java-0.9.0.jar:?]
        at TypeSenseClient.getClient(DefaultRaptorTypeSenseClient.java:132) ~[classes/:?]
        at TypeSenseClient.collectionExists(DefaultRaptorTypeSenseClient.java:40) ~[classes/:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: okhttp3/MediaType
        at org.typesense.api.ApiCall.<clinit>(ApiCall.java:38) ~[typesense-java-0.9.0.jar:?]
        at org.typesense.api.Client.<init>(Client.java:28) ~[typesense-java-0.9.0.jar:?]
```

## Expected Behavior

I expect the dependency for typesense-java to include a dependency for okhttp3 which the library uses internally.

## Actual Behavior

The okhttp3 library seems to be missing, and therefore the code cannot run

## Metadata

**Typesense Version**: 27.0

**OS**: Fedora 40 - Linux

**Comment by phiHero** [comment]
Hi @lm-aols!

I could not reproduce the issue. Which JVM version are you using? Does this also happen in older typesense-java version?

**Comment by lm-aols** [comment]
Hi @phiHero 

My apologies, I've been trying to add typesense-java into the SAP Commerce Cloud framework, where it is possible to declare Maven dependencies, but they have explicitly disabled transitive dependencies and therefore I was missing the required supporting libraries.

https://nurayfahri.medium.com/adding-third-party-dependencies-in-sap-commerce-cloud-using-maven-351162a9489e helped me realize that the error was on my end, and not on this library's end.

**Comment by jasonbosco** [comment]
Thank you for documenting that!
